### ISSUE TITLE
pod error

### ISSUE THREAD

**Issue by rursache** [WishesBest1986/SpringBoard#1]
hello!
incredible work! but please fix pod install, u cannot compile if u pod install the lib.
all good if you import the classes manually

thanks

**Comment by WishesBest1986** [comment]
there is no error when I'm compiled use pod install (The version of my pod is 1.1.1)

**Comment by WishesBest1986** [comment]
may be the example used version is not trunk to pod, you can try next pod version. sorry

**Comment by rursache** [comment]
thank you, pod 0.2.0 fixed it!
