### ISSUE TITLE
4x6 layout system

### ISSUE THREAD

**Issue by rursache** [WishesBest1986/SpringBoard#2]
hello, how can i setup a 4 by 6 icons layout just like 4.7 inch iphones have?
thanks

**Comment by WishesBest1986** [comment]
you can reset springboard.layout, through change itemSize, insets,minimumHorizontalSpace,minimumVerticalSpace properties, you can achieve your aim.

**Comment by rursache** [comment]
i am using

```
_springBoardView.layout.itemSize = CGSizeMake(60, 80);
    _springBoardView.layout.insets = UIEdgeInsetsMake(10, 30, 30, 30);
    _springBoardView.layout.minimumVerticalSpace = 5;
    _springBoardView.layout.minimumHorizontalSpace = 10;
```

but the contrains are not ok even if this is the result i want:

[screenshot](http://imgur.com/a/PTJG8)

if i use 

```
_springBoardView.layout.itemSize = CGSizeMake(60, 60);
```

so i will be square, the layout is a mess:

[screenshot](http://imgur.com/a/FNmyB)

but no contrains error

**Comment by WishesBest1986** [comment]
the Icon Size is fixed to CGSize(70, 70) at this time, I'll change later

**Comment by rursache** [comment]
ok, thank you

**Comment by WishesBest1986** [comment]
Version 0.2.1 is released, WBSpringBoardCell provide method @selector(setImageSize:) to change Cell's ImageView Size( or WBSpringBoardCombinedCell's directoryView Size). At this version, image may out of range of Cell itself, you may try it.

**Comment by rursache** [comment]
wish you all the best and thank you!
